version: 2.1
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run: 
        name: build
        command: |
          set -x
          git clone git@github.com:daseul22/graphql_learn.git
          docker-compose up -d --build
          env
workflows:
  build:
    jobs:
      - build:
        filters:
          branches:
            only: nexus
