version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: build
          command: |
            set -x
            docker build -t graphql:1.0 .
workflows:
  build:
    jobs:
      - build:
        filters:
          branches:
            only: nexus
