version: 2.1
jobs:
  build:
    marchine: true
    steps:
    - checkout
    - run: 
        name: build
        command: |
          set -x
          git clone git@github.com:daseul22/graphql_learn.git
          docker build -t graphql:1.0 .
          env
workflows:
  build:
    jobs:
      - build:
        filters:
          branches:
            only: nexus
